#!/bin/sh

if [ $# -ne 4 ]; then
    echo "Usage: "${0}" <i3_mark> <launch_cmd>" "<x_dimension" "<y_dimension"
    echo "Example: ${0} 'scratch-emacs' 'emacsclient -c -a emacs'" "1200" "800"
    exit 1
fi

I3_MARK=${1}
LAUNCH_CMD=${2}
X_DIM=${3}
Y_DIM=${4}

scratchpad_show() {
    i3-msg "[con_mark=${I3_MARK}]" floating enable
    i3-msg "[con_mark=${I3_MARK}]" resize set ${X_DIM:=1200} ${Y_DIM:=800}
    i3-msg "[con_mark=${I3_MARK}]" sticky enable
    i3-msg "[con_mark=${I3_MARK}]" scratchpad show
}

# try showing the scratchpad window
if ! scratchpad_show; then
    # if there is no such window...

    # launch the application.
    eval "${LAUNCH_CMD}" &
    sleep 0.1

    # Wait for the next window event.
    i3-msg -t subscribe  '[ "window" ]'

    # Set a mark
    i3-msg mark ${I3_MARK}

    # Move it to the scratchpad workspace
    i3-msg move scratchpad

    # show the scratchpad window
    scratchpad_show

    # move window to the center of the screen
    i3-msg "[con_mark=${I3_MARK}]" move position center
fi
