#!/usr/bin/env sh
# requires jq
# failsafe="/tmp/i3-display-swapping"
#
# if [ -e $failsafe ]; then
#   exit 1
# fi
#
# touch $failsafe

if pidof -x blocker >/dev/null 2>&1; then
  exit 1
fi

blocker >/dev/null 2>&1 &

DISPLAY_CONFIG=$(i3-msg -t get_outputs | jq -r '.[]|select(.active == true) |"\(.current_workspace)"')
ACTIVE_WS=$(i3-msg -t get_workspaces | jq -r '.[]|select(.focused == true) | "\(.name)"')
echo "$DISPLAY_CONFIG"
for ROW in $DISPLAY_CONFIG
do
  echo "$ROW"
  i3-msg -- workspace --no-auto-back-and-forth "${ROW}"
  i3-msg -- move workspace to output right
done
i3-msg -- workspace --no-auto-back-and-forth "${ACTIVE_WS}"

sleep 0.5 && killall blocker &
# rm $failsafe
