#!/bin/sh

config="$HOME/.config/kmonad/kmonad.kbd"
keyb1="/dev/input/by-id/usb-Lenovo_ThinkPad_Compact_USB_Keyboard_with_TrackPoint-event-kbd"
killall kmonad

sleep 0.1

setsid -f kmonad $config

sleep 0.1

if test -e $keyb; then
    echo "Activate KMonad for Lenovo Thinkpad keyboard"
    dest="/tmp/kmonad-lenovo.kbd"
    cp $config $dest
    sed -i 's:/dev/input/by-path/platform-i8042-serio-0-event-kbd:'$keyb1':' $dest
    setsid -f kmonad $dest
fi
