#!/bin/sh
# Creation of latex document
cp -f /media/templates/latex/* .

case $1 in
	"") "$EDITOR" latex-report.tex ;;
	*)
		mv report-template.te "$1".tex
		sed -i "1 s/root = report-template\.tex/root = $1\.tex/" _*.tex
		"$EDITOR" "$1".tex
		;;
esac
