#!/bin/sh

# This is bound to Shift+PrintScreen by default, requires maim. It lets you
# choose the kind of screenshot to take, including copying the image or even
# highlighting an area to copy. scrotcucks on suicidewatch right now.

case "$1" in
	"selected") maim -s pic-selected-"$(date '+%y%m%d-%H%M-%S').png" ;;
	"current") maim -i "$(xdotool getactivewindow)" pic-window-"$(date '+%y%m%d-%H%M-%S').png" ;;
	"fullscreen") maim pic-full-"$(date '+%y%m%d-%H%M-%S').png" ;;
	"selected(copy)") maim -s | xclip -selection clipboard -t image/png ;;
	"current(copy)") maim -i "$(xdotool getactivewindow)" | xclip -selection clipboard -t image/png ;;
	"fullscreen(copy)") maim | xclip -selection clipboard -t image/png ;;
esac
