#!/bin/sh

# This is bound to Shift+PrintScreen by default, requires maim. It lets you
# choose the kind of screenshot to take, including copying the image or even
# highlighting an area to copy. scrotcucks on suicidewatch right now.

output=${XDG_PICTURES_DIR:="$HOME/pix"}/screenshots/"$(date +%s_%h%d_%H:%M:%S).png"

take_screenshot() {
	case "$1" in
		"Selected") maim --hidecursor -s "$output" ;;
		"Current") maim --hidecursor -i "$(xdotool getactivewindow)" "$output" ;;
		"Fullscreen") maim --hidecursor "$output" ;;
		"Selected (copy)") maim --hidecursor -s | xclip -selection clipboard -t image/png ;;
		"Current (copy)") maim --hidecursor -i "$(xdotool getactivewindow)" | xclip -selection clipboard -t image/png ;;
		"Fullscreen (copy)") maim --hidecursor | xclip -selection clipboard -t image/png ;;
	esac
}

notify_success() {
	if [ "$(echo "$1" | cut -d" " -f2)" = "(copy)" ]; then
		notify-send "Screenshot copied to clipboard"
	else
		notify-send "Screenshot saved at $output"
	fi
}

take_screenshot "$@" && notify_success "$@"
