#!/bin/sh
pamixer --list-sources | grep input | awk '{print $1}' |
	while read -r index; do
		mic_muted="$(pamixer --source "$index" --get-mute)"
		if [ "$mic_muted" = "true" ]; then
			pamixer --source "$index" -u
		else
			pamixer --source "$index" -m
		fi
	done
# sb-refresh sb-microphone
# duskc --ignore-reply run_command setstatus 3 "$(sb-microphone)"
# polybar-msg hook microphone 1
# canberra-gtk-play -i audio-volume-change
