#!/bin/sh
pamixer --list-sources | grep input | awk '{print $1}' |
	while read -r index; do
		mic_muted="$(pamixer --source "$index" --get-mute)"
		if [ "$mic_muted" = "true" ]; then
			if [ "$1" = "toggle" ]; then
				pamixer --source "$index" -u
				polybar-msg hook microphone 1
				canberra-gtk-play -i audio-volume-change
			else
				echo ""
			fi
		else
			if [ "$1" = "toggle" ]; then
				pamixer --source "$index" -m
				polybar-msg hook microphone 2
				canberra-gtk-play -i audio-volume-change
			else
				echo ""
			fi
		fi
	done
# sb-refresh sb-microphone
# duskc --ignore-reply run_command setstatus 3 "$(sb-microphone)"
