#!/bin/sh

# xrandr --setprovideroutputsource modesetting NVIDIA-0
# xrandr --auto
xrandr --output eDP-1-1 --primary --mode 1920x1080 --rotate normal --output DP-1-1 --off
xrandr --output HDMI-0 --mode 1366x768 --left-of eDP-1-1 --rotate normal 
