#!/bin/sh

xrandr --setprovideroutputsource modesetting NVIDIA-0
# xrandr --auto
xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --off --output VIRTUAL1 --off --output HDMI-1-0 --mode 1920x1080 --pos 1920x0 --rotate normal
