#!/bin/sh
# make CapsLock behave like Ctrl:
#setxkbmap -option ctrl:nocaps
#setxkbmap us -variant colemak

# make short-pressed Ctrl behave like Escape:
#xcape -e 'Control_L=Escape'

# This script is called on startup to remap keys.
# Increase key speed via a rate change
xset r rate 300 40
