#!/bin/sh
# A dmenu wrapper script for system functions.
case "$(readlink -f /sbin/init)" in
	*systemd*) ctl='systemctl' ;;
	*) ctl='loginctl' ;;
esac

case "$(printf "🔒 lock\n🚪 leave xmonad\n♻️ renew xmonad\n🐻 hibernate\n🔃 reboot\n🖥️shutdown\n💤 sleep\n📺 display off" | dmenu -i -p 'Action: ')" in
	'🔒 lock') slock ;;
	'🚪 leave xmonad') kill -TERM "$(pgrep -u "$USER" "\bxmonad$")" ;;
	'♻️ renew xmonad') kill -HUP "$(pgrep -u "$USER" "\bxmonad$")" ;;
	'🐻 hibernate') slock $ctl hibernate ;;
	'💤 sleep') slock $ctl suspend ;;
	'🔃 reboot') $ctl reboot -i ;;
	'🖥️shutdown') $ctl poweroff -i ;;
	'📺 display off') xset dpms force off ;;
	*) exit 1 ;;
esac
