#!/bin/sh
# A dmenu wrapper script for system functions.
#
wm="i3"

logout_menu() {
	printf "%s\n" \
		"1.  Lock" \
		"2.  Refresh sxhkd" \
		"3.  Configure drawing tablet" \
		"4.  Leave $wm" \
		"5.  Reboot" \
		"6.  Shutdown" |
		dmenu -l 6 -p 'Action: '
}

case "$(readlink -f /sbin/init)" in
	*systemd*) ctl='systemctl' ;;
	*) ctl='loginctl' ;;
esac

case $(logout_menu | awk -F"." '{print $1}') in
	"1") slock ;;
	"2") pidof sxhkd && pkill -SIGUSR1 sxhkd || setsid -f sxhkd ;;
	"3") dm-wacom --interactive ;;
	"4") pgrep $wm && pkill $wm ;;
	"5") $ctl reboot -i ;;
	"6") $ctl poweroff -i ;;
	*) exit 1 ;;
esac
