#!/bin/sh

sed -n '/START_KEYS/,/END_KEYS/p' ~/.config/xmonad/xmonad.hs |
	grep '^\s*(\|^\s*\-\- [A-Za-z]\|^\s*,\s*(\|^$' |
	sed -e 's/^\s*,\s*//' \
		-e 's/^\s*//' |
	awk -F", " '! /^\s*\-\-/ {$1 = sprintf("%-30s", $1)} 1' |
	yad --text-info --back=#1E1E1E --fore=#D8DEE9 --geometry=1200x800 --lang haskell --theme "Oblivion"
