#!/bin/sh

wikidir="/usr/share/doc/arch-wiki/html/en/"
wikidocs="$(fd --type file --strip-cwd-prefix --base-directory $wikidir)"

choice=$(printf "%s\n" "$wikidocs" | \
             sed "s/.html//g" | \
             sort -g | \
             dmenu -l 20 -p "Arch Wiki Docs: ") || exit 1

if [ "$choice" ]; then
    article=$(printf "%s%s.html" "$wikidir" "$choice")
    emacsclient -c -n --eval "(eww-open-file \"$article\")" >/dev/null
else
    echo "Program terminated." && exit 0
fi
