#!/bin/sh

choice() {
    printf "%s\n"
}

xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output DP1 --off --output VIRTUAL1 --off --output HDMI-1-0 --mode 1366x768 --left-of eDP1 --rotate normal
